// 定义状态码
export enum APP_CODES {
    HEALTY = "HEALTY",
    USER_CREATE = "USER_CREATE",
    NOT_JSON = "NOT_JSON",
    NO_EMAIL_OR_PASSWORD = "NO_EMAIL_OR_PASSWORD",
    EMAIL_FORMAT = "EMAIL_FORMAT",
    EMAIL_EXISTS = "EMAIL_EXISTS",
    USER_ERROR = "USER_ERROR",
}
